name: "Lint PR title"
# Can run on public GH actions runner
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - 'main'
jobs:
  lint:
    if: ${{ github.head_ref != 'main' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install @commitlint/cli @commitlint/config-conventional

    - name: WTF
      run: | 
        pwd
        ls -alh

    - name: Validate PR title
      run: |
        PR_TITLE=$(jq -r '.pull_request.title' "$GITHUB_EVENT_PATH")
        echo "$PR_TITLE" | npx commitlint --config commitlint.config.js