# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions
name: Weekly bounce
on:
  schedule:
    - cron: '0 0 * * 0'

env:
  REGISTRY_USER: rh-ee-chbutler
  IMAGE_REGISTRY: quay.io
  IMAGE: rhel-dev-arm

jobs:
  buildrelease:
    runs-on: ubuntu-24.04-arm
    container:
      image: registry.access.redhat.com/ubi9/ubi
      options: --privileged    
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Get latest v* tag
      id: get_latest_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0 --match "v*" || echo "v0.0.0")
        echo "Latest tag: $latest_tag"
        clean_version=${latest_tag#v}  # Remove leading 'v'
        echo "Clean version: $clean_version"
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_OUTPUT
        echo "VERSION=$clean_version" >> $GITHUB_OUTPUT
    - name: Checkout latest tag
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.get_latest_tag.outputs.LATEST_TAG }}
        
    - name: Get container tools in UBI builder
      run: dnf -y install podman buildah skopeo make wget
    - name: Access a subscription via activation key
      env:
        SMDEV_CONTAINER_OFF: 1
        orgid: ${{ secrets.RHT_ORGID }}
        activation_key: ${{ secrets.RHT_ACT_KEY }}

      run: subscription-manager register --org=$orgid --activationkey=$activation_key
    - name: Workaround open podman-login action issue
      env:
        auth: "{ \"auths\": {} }"
      run: |
        mkdir -p $HOME/.docker
        echo $auth > $HOME/.docker/config.json

    
    - name: Log in to Quay.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{ env.IMAGE_REGISTRY }}
        auth_file_path: /run/containers/0/auth.json
    - name: Log in to registry.redhat.io
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.RH_REGISTRY_USER }} # service account
        password: ${{ secrets.RH_REGISTRY_PASSWORD }} # service accounts
        registry: registry.redhat.io
        auth_file_path: /run/containers/0/auth.json
    - name: Pull deps
      run: make get-deps

    - name: Build Image
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: "quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}"
        tags: latest prod ${{ steps.parse_version.outputs.VERSION }} ${{ github.sha }}
        containerfiles: |
          ./Containerfile
  
    - name: Install Cosign
      uses: sigstore/cosign-installer@v3.7.0
    
    - name: push to registry
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ env.IMAGE }}
        tags: latest prod ${{ steps.parse_version.outputs.VERSION }} ${{ github.sha }} 
        registry: quay.io/${{ env.REGISTRY_USER }}
    
    - name: what would we sign
      run: podman image inspect --format '{{ .Digest }}' quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}
      
    - name: Sign image
      #run: cosign sign  --yes -a tag=${{ steps.parse_version.outputs.VERSION }} -a tag=prod -a tag=latest -a tag=${{ github.sha }} -a sha=${{ github.sha }} -a run_id=${{github.run_id}} -a run_attempt="$GITHUB_RUN_ATTEMPT" quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}@`podman image inspect --format '{{ .Digest }}' quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}`
      run: cosign sign  --yes -a tag=${{ steps.parse_version.outputs.VERSION }} -a tag=prod -a tag=latest -a tag=${{ github.sha }} -a sha=${{ github.sha }} -a run_id=${{github.run_id}} -a run_attempt="$GITHUB_RUN_ATTEMPT" quay.io/${{ env.REGISTRY_USER }}/${{ env.IMAGE }}:prod
    - name: Clean up the subscription
      if: always()
      env:
        SMDEV_CONTAINER_OFF: 1
      run: subscription-manager unregister